source( 'best.R' )
source( 'rankhospital.R' )
source( 'rankall.R' )

options( error=expression( NULL ) )
best( 'TX', 'heart attack' )
best( 'TX', 'heart failure' )
best( 'MD', 'heart attack' )
best( 'MD', 'pneumonia' )
best( 'BB', 'heart attack' )
best( 'NY', 'hert attack' )

rankhospital( 'A', 'B', 1 )
rankhospital( 'TX', 'B', 1 )
rankhospital( 'TX', 'heart attack', 'A')
rankhospital( 'TX', 'heart failure', 4 )
rankhospital( 'MD', 'heart attack', 'worst' )
rankhospital( 'MN', 'heart attack', 5000 )

rankall( 'B', 1 )
rankall( 'heart attack', 'A')
head( rankall( 'heart attack', 20 ), 10 )
tail( rankall( 'pneumonia', 'worst' ), 3 )
tail( rankall( 'heart failure' ), 10 )
options( error=NULL )
